"""add photo url

Revision ID: 9b5641279252
Revises: 3bc55439975d
Create Date: 2022-01-25 10:23:10.449213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b5641279252"
down_revision = "3bc55439975d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("complaints", sa.Column("photo_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "photo_url")
    # ### end Alembic commands ###
