"""add transactions

Revision ID: a666c5b8f53a
Revises: 9b5641279252
Create Date: 2022-01-27 09:29:30.073347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a666c5b8f53a"
down_revision = "9b5641279252"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=128), nullable=False),
        sa.Column("transfer_id", sa.Integer(), nullable=False),
        sa.Column("target_account_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###
